on: [push, pull_request]
name: CI
jobs:
  test:
    name: Test
    strategy:
      matrix:
        go-version: [1.21.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Verify Go Version & Modules
        run: |
          go version
          ls -la
          cat go.mod || echo "go.mod not found"

      - name: Build
        run: go build -v -o /dev/null .

      - name: Test
        run: go test -v ./...

