name: CI
on:
  pull_request: {}
  push: {}
permissions: write-all
jobs:
  # ================
  # BUILD AND TEST JOB
  # ================
  test:
    name: Build & Test
    strategy:
      matrix:
        go-version: [1.21.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build
        run: go build -v -o /dev/null .
      - name: Test
        run: go test -v ./...
